# Generated by Django 3.1.6 on 2021-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20210401_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='inTime',
            field=models.DateTimeField(),
        ),
    ]
