# Generated by Django 3.1.6 on 2021-03-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTracing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSeen', models.DateTimeField(auto_now=True)),
                ('epochTime', models.FloatField()),
                ('tag1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag1id', to='asset.asset')),
                ('tag2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag2id', to='asset.asset')),
            ],
        ),
    ]
