# Generated by Django 3.1.6 on 2021-03-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('tagId', models.CharField(max_length=30, unique=True)),
                ('registrationNo', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('mailId', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('battery', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
    ]
