# Generated by Django 3.1.6 on 2021-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assethealth',
            old_name='asset',
            new_name='tagId',
        ),
        migrations.AlterField(
            model_name='assethealth',
            name='lastseen',
            field=models.DateTimeField(),
        ),
    ]
